parameters:
    locale: 'en'

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Belga\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Belga\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    exception_listener:
        class: Belga\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    event_listener.request:
        class: Belga\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments: ["@api_key_authenticator"]

    api_key_authenticator:
        class: Belga\Security\ApiKeyAuthenticator
        arguments: ['%apikeys%', '@logger']